stages:
  - validate
  - plan
  # - apply
  # - output
  - lint
  - checkov
  # - destroy

image:
  name: hashicorp/terraform:light
  entrypoint:
    - "/usr/bin/env"
    - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

before_script:
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - terraform --version
   # Install tflint using curl
   # Install tflint using curl
  - curl -sLo tflint.zip https://github.com/terraform-linters/tflint/releases/download/v0.43.0/tflint_linux_amd64.zip
  - unzip tflint.zip
  - chmod +x tflint
  - ./tflint --version
validate:
  stage: validate
  script:
    - cd DiplomnaRabota/terraform
    - terraform init
    - terraform validate
  tags:
    - ci-shared

plan:
  stage: plan
  script:
    - cd DiplomnaRabota/terraform
    - terraform init
    - terraform plan
  dependencies:
    - validate
  tags:
    - ci-shared

# apply:
#   stage: apply
#   script:
#     - cd DiplomnaRabota/terraform
#     - terraform init
#     - terraform apply -auto-approve
#   dependencies:
#     - plan
#   tags:
#     - ci-shared

# output:
#   stage: output
#   script:
#     - cd DiplomnaRabota/terraform
#     - terraform output
#   dependencies:
#     - apply
#   tags:
#     - ci-shared

lint:
  stage: lint
  script:
    - cd DiplomnaRabota/terraform
    - /home/gitlab-runner/builds/uZaqzEMz/0/elsys/petar-petrov/tflint --config ./tflint.hcl
    - tflint
  tags:
    - ci-shared

checkov:
  stage: checkov
  script:
    - cd DiplomnaRabota/terraform
    - checkov -d . --framework terraform
  tags:
    - ci-shared

# destroy:
#   stage: destroy
#   script:
#     - cd DiplomnaRabota/terraform
#     - terraform destroy -auto-approve
#   when: manual
#   tags:
#     - ci-shared
