stages:
  - validate
  - plan
  - apply

variables:
  TF_IN_AUTOMATION: "true"
  TF_LOG: "INFO"

validate:
  stage: validate
  tags:
    - ci-shared
  script:
    - cd DiplomnaRabota/terraform    
    - terraform init                 
    - terraform validate             

plan:
  stage: plan
  tags:
    - ci-shared  # Този таг трябва да съвпадне с таг на вашия runner
  script:
    - cd DiplomnaRabota/terraform     
    - terraform init                 
    - terraform plan                 

  only:
    - main                           
