apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring  # Ensure this is set to monitoring
spec:
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
  selector:
    app: postgres-exporter
