apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ppetrov06/interview_preparation_app:frontend
        ports:
        - containerPort: 3001
        env:
        - name: BACKEND_URL
          value: "http://backend:5000"  
        - name: PORT
          value: "3001"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: frontend
  type: NodePort
